/** DO NOT EDIT THIS FILE **/
public class ASCVD {
	/* Attributes */
	private int sbp, age, cholesterol, hdl;
	private boolean female, white, treated, diabetes, smoker;
	/* Constants */
	private static final double[] fw = {-29.799, 4.884, 13.540,-3.114,-13.578, 3.149,  2.019, 0.0  ,  1.957, 0.0  , 7.574,-1.665, 0.661,-29.18, 0.9665};
	private static final double[] fb = { 17.114, 0.0  ,  0.940, 0.0  ,-18.920, 4.475, 29.291,-6.432, 27.820,-6.087, 0.691, 0.0  , 0.874, 86.61, 0.9533};
	private static final double[] mw = { 12.344, 0.0  , 11.853,-2.664, -7.990, 1.769,  1.797, 0.0  ,  1.764, 0.0  , 7.837,-1.795, 0.658, 61.18, 0.9144};
	private static final double[] mb = {  2.469, 0.0  ,  0.302, 0.0  , -0.307, 0.0  ,  1.916, 0.0  ,  1.809, 0.0  , 0.549, 0.0  , 0.645, 19.54, 0.8954};
	/* Constructor */
	public ASCVD() {
		sbp=140;
		age=40;
		cholesterol=200;
		hdl=100;
		female=false;
		white=false;
		treated=false;
		diabetes=false;
		smoker=false;
	}
	/* Getters */
	public int getSBP() { return sbp; }
	public int getAge() { return age; }
	public int getCholesterol() { return cholesterol; }
	public int getHDL() { return hdl; }
	public boolean getFemale() { return female; }
	public boolean getWhite() { return white; }
	public boolean getTreated() { return treated; }
	public boolean getDiabetes() { return diabetes; }
	public boolean getSmoker() { return smoker; }
	/* Setters */
	public void setSBP(int newSBP) { if(newSBP>=60 && newSBP<=300) sbp=newSBP; }
	public void setAge(int newAge) { if(newAge>=40 && newAge<=79) age=newAge; }
	public void setCholesterol(int newCholesterol) { if(newCholesterol>=100 && newCholesterol<=999) cholesterol=newCholesterol; }
	public void setHDL(int newHDL) { if(newHDL>=10 && newHDL<150) hdl=newHDL; }
	public void setFemale(boolean newFemale) { female = newFemale; }
	public void setWhite(boolean newWhite) { white = newWhite; }
	public void setTreated(boolean newTreated) { treated = newTreated; }
	public void setDiabetes(boolean newDiabetes) { diabetes = newDiabetes; }
	public void setSmoker(boolean newSmoker) { smoker = newSmoker; }
	/**
	* Calculates 10-year ASCVD risk percentage.
	* @return 10 year risk percent as a double. Example: 0.142 is 14.2%.
	*/
	public double getRisk() {
		double[] c = new double[15];
		double sum=0;
		if( female &&  white) System.arraycopy(fw, 0, c, 0, 15);
		if( female && !white) System.arraycopy(fb, 0, c, 0, 15);
		if(!female &&  white) System.arraycopy(mw, 0, c, 0, 15);
		if(!female && !white) System.arraycopy(mb, 0, c, 0, 15);
		c[0]*= Math.log(age);
		c[1]*= Math.pow(Math.log(age),2);
		c[2]*= Math.log(cholesterol);
		c[3]*= Math.log(age)*Math.log(cholesterol);
		c[4]*= Math.log(hdl);
		c[5]*= Math.log(age)*Math.log(hdl);
		if(treated) {
			c[6]*= Math.log(sbp);
			c[7]*= Math.log(age)*Math.log(sbp);
			c[8] = 0;
			c[9] = 0;
		} else {
			c[6] = 0;
			c[7] = 0;
			c[8]*= Math.log(sbp);
			c[9]*= Math.log(age)*Math.log(sbp);
		}
		if(smoker) {
			c[11]*= Math.log(age);
		} else {
			c[10] = 0;
			c[11] = 0;
		}
		if(!diabetes) {
			c[12] = 0;
		}
		for(int i=0; i<13; i++) sum+= c[i];
		return 1.0 - Math.pow(c[14], Math.exp(sum - c[13]));
	}
}
