/** Do not edit this file                                   **/
/** You won't turn in this file.                            **/
/** This is ONLY used to test your Intersection.java class. **/
import java.util.Random;
public class Lab9 {
	public static void main(String[] args) {
		Intersection intersection = new Intersection();
		Random rand = new Random();
		for(int i=0; i<200; i++) {
			int d = rand.nextInt(10);
			if(d==0) intersection.add('N', i%10);
			else if(d==1) intersection.add('E', i%10);
			else if(d==2) intersection.add('S', i%10);
			else if(d==3) intersection.add('W', i%10);
			else intersection.poll();
			System.out.println("Step "+i+", the intersection is:");
			System.out.println(intersection);
		}
	}
}
